In [5]:
#NUMPY


In [6]:
numpy stands for numerical python

SyntaxError: invalid syntax (Temp/ipykernel_7584/4133749262.py, line 1)

In [7]:
it is a python library

SyntaxError: invalid syntax (Temp/ipykernel_7584/1394838534.py, line 1)

In [8]:
consisting of multidimensional array objects and a collection of routines for processing of arrays

SyntaxError: invalid syntax (Temp/ipykernel_7584/1493959131.py, line 1)

In [9]:
there are many contributors to this open project

SyntaxError: invalid syntax (Temp/ipykernel_7584/462271089.py, line 1)

In [10]:

#Difference b/w list and numpy


In [11]:
LIST:-
    able to store different datatypes in the same list
    soring each item in random location in the memory
    good for the scenario where list can grow dynamically
    inbuilt datatype
    it has more inbuilt functions
    appending will take less time in 0(1) time

SyntaxError: invalid syntax (Temp/ipykernel_7584/3821107916.py, line 1)

In [12]:
NUMPY OR ARRAY:-
    can store only one datatype in an array at anytime
    storing each item is sequential which makes array more effective in processing
    good for scenario where the items are fixed size and same data time
    need to install external library numpy
    no extra functions so it will not store more memory
    appending elements will take more time in 0(n) time
    

SyntaxError: invalid syntax (Temp/ipykernel_7584/4101909424.py, line 1)

In [13]:
Array is faster than list

SyntaxError: invalid syntax (Temp/ipykernel_7584/2013897719.py, line 1)

In [14]:
!pip install numpy
import numpy as np

In [15]:
l1=[20,40,60]
l2=[10,30,50]
l3=np.array(l1)
l4=np.array(l2)
print(l3)
print(l4)


[20 40 60]
[10 30 50]


In [16]:
print(type(l3))

<class 'numpy.ndarray'>


In [22]:
#Creating numpy array
There are multiple ways to create numpy array
1.Using arrange() fns
    

SyntaxError: invalid syntax (Temp/ipykernel_7584/3702985111.py, line 2)

In [23]:
np.arange(5,15)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [24]:
np.arange(5,11,6)

array([5])

In [25]:
2.Using eye()fn

SyntaxError: invalid syntax (Temp/ipykernel_7584/996712509.py, line 1)

In [26]:
np.eye (10,dtype=float)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [27]:
3.zeros()fn

SyntaxError: invalid syntax (Temp/ipykernel_7584/3505060536.py, line 1)

In [28]:
np.zeros((4,2),dtype=int)

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0]])

In [29]:
4.ones()fn

SyntaxError: invalid syntax (Temp/ipykernel_7584/3790165962.py, line 1)

In [30]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [31]:
np.full((3,5),10) #using full()fn

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [33]:
x=[1,2,3,4,5,6,7] #diagonal()fn
np.diag(x)

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0],
       [0, 0, 0, 0, 0, 6, 0],
       [0, 0, 0, 0, 0, 0, 7]])

In [37]:
np.linspace(1,20, num=30)#linspace()fn

array([ 1.        ,  1.65517241,  2.31034483,  2.96551724,  3.62068966,
        4.27586207,  4.93103448,  5.5862069 ,  6.24137931,  6.89655172,
        7.55172414,  8.20689655,  8.86206897,  9.51724138, 10.17241379,
       10.82758621, 11.48275862, 12.13793103, 12.79310345, 13.44827586,
       14.10344828, 14.75862069, 15.4137931 , 16.06896552, 16.72413793,
       17.37931034, 18.03448276, 18.68965517, 19.34482759, 20.        ])

In [41]:
np.random.randint(0,50)#random nos

34

In [42]:
np.random.randn(3,3)

array([[ 0.403079  ,  0.00320061, -0.23217175],
       [-0.6711556 ,  1.08154155, -0.53656013],
       [ 0.73361423, -0.51761221,  0.8446717 ]])

In [43]:
x=np.arange(8,18) #reshape()fn
print(x)
print(x.shape)

[ 8  9 10 11 12 13 14 15 16 17]
(10,)


In [48]:
n=x.reshape(2,5)

print(n.shape)

(2, 5)


In [49]:
#Ravel fn
ravel means getting back to previous
ravel=undo

SyntaxError: invalid syntax (Temp/ipykernel_7584/2665365982.py, line 2)

In [50]:
v=n.ravel()
print(v.shape)
print(v)

(10,)
[ 8  9 10 11 12 13 14 15 16 17]


In [54]:
x1=np.arange(10) #numpy copy vs view
x2=x1
print(x1)
print(x2)


[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [55]:
print(np.shares_memory(x1,x2))
print(id(x1))
print(id(x2))

True
2312243770736
2312243770736


In [56]:
x3=x1.view()

In [63]:
a=[1,2,3] #horizontalstack
b=[4,5,6]
(a,b)=([1,2,3],[4,5,6])
np.hstack((a,b))
     
    


array([1, 2, 3, 4, 5, 6])

In [64]:
np.vstack((a,b)) #verticalstack

array([[1, 2, 3],
       [4, 5, 6]])

In [68]:
print(x1)
print(x2)
np.insert(x1,4,x2)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


array([0, 1, 2, 3, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 4, 5, 6, 7, 8, 9])

In [69]:
print(x1)
np.delete(x1,2)

[0 1 2 3 4 5 6 7 8 9]


array([0, 1, 3, 4, 5, 6, 7, 8, 9])

In [71]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
np.cos(a)

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029],
       [ 0.75390225, -0.14550003, -0.91113026]])

In [72]:
np.sin(a)

array([[ 0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ],
       [ 0.6569866 ,  0.98935825,  0.41211849]])

In [73]:
np.tan(a)

array([[ 1.55740772, -2.18503986, -0.14254654],
       [ 1.15782128, -3.38051501, -0.29100619],
       [ 0.87144798, -6.79971146, -0.45231566]])

In [74]:
np.sum(a)

45

In [75]:
np.sum(a,axis=1)

array([ 6, 15, 24])

In [76]:
np.sum(a,axis=0)

array([12, 15, 18])

In [77]:
np.median(a)

5.0

In [79]:
np.mean(a)

5.0

In [80]:
np.std(a)

2.581988897471611

In [81]:
np.max(a)

9